<a id="TOP"> </a>
<div class= "alert alert-box alert-info">
</div>

***
# Exercises

[__Section 1 |__](#1)
[__Section 2 |__](#2)
[__Section 3 |__](#3)
[__Section 4 |__](#4)
[__Section 5 |__](#5)
[__Section 6 |__](#6)
[__Section 7__](#7)

**Create a new local git repository and remote repository on github named `time-series-exercises`. Save this work for this module in your `time-series-exercises` repo.**

**The end result of this exercise should be a file named `acquire.py`.**

<a id="Lesson"> </a>
<div class= "alert alert-box alert-info">
</div>

***

In [1]:
import requests
import pandas as pd
import numpy as np
from acquire import pznet_api, all_sales, open_power_systems_data

<a id="1"> </a>
<div class= "alert alert-box alert-info">
</div>

***
## 1. Using the code from the lesson as a guide and the REST API from [items](https://python.zgulde.net/api/v1/items) as we did in the lesson, create a dataframe named items that has all of the data for items.

In [2]:
items = pznet_api('items')
items

,item_brand,item_id,item_name,item_price,item_upc12,item_upc14
0,Riceland,1,Riceland American Jazmine Rice,0.84,35200264013,35200264013
1,Caress,2,Caress Velvet Bliss Ultra Silkening Beauty Bar...,6.44,11111065925,11111065925
2,Earths Best,3,Earths Best Organic Fruit Yogurt Smoothie Mixe...,2.43,23923330139,23923330139
3,Boars Head,4,Boars Head Sliced White American Cheese - 120 Ct,3.14,208528800007,208528800007
4,Back To Nature,5,Back To Nature Gluten Free White Cheddar Rice ...,2.61,759283100036,759283100036
5,Sally Hansen,6,Sally Hansen Nail Color Magnetic 903 Silver El...,6.93,74170388732,74170388732
6,Twinings Of London,7,Twinings Of London Classics Lady Grey Tea - 20 Ct,9.64,70177154004,70177154004
7,Lea & Perrins,8,Lea & Perrins Marinade In-a-bag Cracked Pepper...,1.68,51600080015,51600080015
8,Van De Kamps,9,Van De Kamps Fillets Beer Battered - 10 Ct,1.79,19600923015,19600923015
9,Ahold,10,Ahold Cocoa Almonds,3.17,688267141676,688267141676
10,Honest Tea,11,Honest Tea Peach White Tea,3.93,657622604842,657622604842
11,Mueller,12,Mueller Sport Care Basic Support Level Medium ...,8.40,74676640211,74676640211
12,Garnier Nutritioniste,13,Garnier Nutritioniste Moisture Rescue Fresh Cl...,6.47,603084234561,603084234561
13,Pamprin,14,Pamprin Maximum Strength Multi-symptom Menstru...,7.54,41167300121,41167300121
14,Suave,15,Suave Naturals Moisturizing Body Wash Creamy T...,9.11,79400847201,79400847201
15,Burts Bees,16,Burts Bees Daily Moisturizing Cream Sensitive,5.17,792850014008,792850014008
16,Ducal,17,Ducal Refried Red Beans,1.16,88313590791,88313590791
17,Scotch,18,Scotch Removable Clear Mounting Squares - 35 Ct,4.39,21200725340,21200725340
18,Careone,19,Careone Family Comb Set - 8 Ct,0.74,41520035646,41520035646
19,Usda Produce,20,Plums Black,5.62,204040000000,204040000000
20,Doctors Best,21,Doctors Best Best Curcumin C3 Complex 1000mg T...,8.09,753950001954,753950001954
21,Betty Crocker,22,Betty Crocker Twin Pack Real Potatoes Scallope...,7.31,16000288829,16000288829
22,Reese,23,Reese Mandarin Oranges Segments In Light Syrup,1.78,70670009658,70670009658
23,Smart Living,24,Smart Living Charcoal Lighter Fluid,5.34,688267084225,688267084225
24,Hood,25,Hood Latte Iced Coffee Drink Vanilla Latte,2.43,44100117428,44100117428
25,Triaminic,26,Triaminic Syrup Night Time Cold & Cough Grape 4oz,0.98,300436344045,300436344045
26,Morton,27,Morton Kosher Salt Coarse,6.01,24600017008,24600017008
27,Usda Produce,28,Guava,7.52,719175900007,719175900007
28,Heinz,29,Heinz Tomato Ketchup - 2 Ct,8.65,13000001038,13000001038
29,Petmate,30,Petmate Booda Bones Steak Bacon & Chicken Flav...,8.39,723503568678,723503568678
30,Zhenas Gypsy Tea,31,Zhenas Gypsy Tea Herbal Red Tea Sachets Fire L...,4.21,652790100226,652790100226
31,Barefoot,32,Barefoot Pinot Grigio 187,0.68,8500004528,8500004528
32,The First Years,33,Tomy The First Years Gumdrop Orthodontic Pacif...,6.52,71463060078,71463060078
33,Halls,34,Halls Menthol Cough Suppresant/oral Anesthetic...,4.17,312546628694,312546628694
34,Natures Way,35,Natures Way Forskohlii - 60 Ct,5.19,33674100066,33674100066
35,Deerfields Gluten Free,36,Rice Bran Gluten Free Dinner Rolls Plain,7.95,610358991525,610358991525
36,Nakano,37,Nakano Seasoned Rice Vinegar Original,9.59,73575295003,73575295003
37,Sundown Naturals,38,Sundown Naturals Essential Electrolytes Tropic...,3.45,30768540548,30768540548
38,Munchies,39,Munchies Sandwich Crackers Cheddar Cheese On G...,9.02,28400029254,28400029254
39,Amys,40,Amys Light & Lean Spaghetti Italiano,0.60,42272008063,42272008063
40,P.f. Changs,41,P.f. Changs Home Menu Meal For Two Beef With B...,5.62,31000670016,31000670016
41,Moms Best Naturals,42,Moms Best Naturals Cereal Toasted Cinnamon Squ...,2.97,883978129115,883978129115
42,Ferrara,43,Ferrara Vanilla Syrup,8.40,71403000379,71403000379
43,Elmers,44,Elmers Board Mate Dual Tip Glue Pen,7.06,26000001403,26000001403
44,Kelloggs,45,Kelloggs Disney Pixar Cars 2 Cereal,4.40,38000542237,38000542237
45,Mama Marys,46,Pizza Sauce,4.65,35457770664,35457770664
46,Bear Naked,47,Bear Naked Fit Almond Crisp 100 Percent Natura...,7.38,884623708976,884623708976
47,Dove,48,Dove Men + Care Antiperspirant Deodorant Cool ...,3.72,79400271631,79400271631
48,Easy-off,49,Easy-off Oven Cleaner Lemon Scent,9.54,62338879772,62338879772
49,Choice,50,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221

<a id="2"> </a>
<div class= "alert alert-box alert-info">
</div>

***
## 2. Do the same thing, but for [stores](https://python.zgulde.net/api/v1/stores)

[__<u>TOP</u>__](#TOP)

In [3]:
stores = pznet_api('stores')
stores

             store_address   store_city  store_id store_state store_zipcode
0   12125 Alamo Ranch Pkwy  San Antonio         1          TX         78253
1         9255 FM 471 West  San Antonio         2          TX         78251
2  2118 Fredericksburg Rdj  San Antonio         3          TX         78201
3          516 S Flores St  San Antonio         4          TX         78204
4          1520 Austin Hwy  San Antonio         5          TX         78218
5       1015 S WW White Rd  San Antonio         6          TX         78220
6   12018 Perrin Beitel Rd  San Antonio         7          TX         78217
7      15000 San Pedro Ave  San Antonio         8          TX         78232
8       735 SW Military Dr  San Antonio         9          TX         78221
9     8503 NW Military Hwy  San Antonio        10          TX         78231

<a id="3"> </a>
<div class= "alert alert-box alert-info">
</div>

***
## 3. Extract the data for [sales](https://python.zgulde.net/api/v1/sales). There are a lot of pages of data here, so your code will need to be a little more complex. Your code should continue fetching data from the next page until all of the data is extracted.

[__<u>TOP</u>__](#TOP)

In [4]:
sales = pznet_api('sales')

sales

        item  sale_amount                      sale_date  sale_id  store
0          1         13.0  Tue, 01 Jan 2013 00:00:00 GMT        1      1
1          1         11.0  Wed, 02 Jan 2013 00:00:00 GMT        2      1
2          1         14.0  Thu, 03 Jan 2013 00:00:00 GMT        3      1
3          1         13.0  Fri, 04 Jan 2013 00:00:00 GMT        4      1
4          1         10.0  Sat, 05 Jan 2013 00:00:00 GMT        5      1
...      ...          ...                            ...      ...    ...
912995    50         63.0  Wed, 27 Dec 2017 00:00:00 GMT   912996     10
912996    50         59.0  Thu, 28 Dec 2017 00:00:00 GMT   912997     10
912997    50         74.0  Fri, 29 Dec 2017 00:00:00 GMT   912998     10
912998    50         62.0  Sat, 30 Dec 2017 00:00:00 GMT   912999     10
912999    50         82.0  Sun, 31 Dec 2017 00:00:00 GMT   913000     10

[913000 rows x 5 columns]

<a id="4"> </a>
<div class= "alert alert-box alert-info">
</div>

***
## 4. Save the data in your files to local csv files so that it will be faster to access in the future.

[__<u>TOP</u>__](#TOP)

In [ ]:
sales = pd.read_pickle('sales')
sales.head()

In [ ]:
stores = pd.read_pickle('stores')
stores.head()

In [ ]:
items = pd.read_pickle('items')
items.head()

<a id="5"> </a>
<div class= "alert alert-box alert-info">
</div>

***
## 5. Combine the data from your three separate dataframes into one large dataframe.

[__<u>TOP</u>__](#TOP)

In [7]:
from wrangle import summarize

In [ ]:
# summarize(sales, q=5)

In [ ]:
# summarize(stores, q=5)

In [ ]:
# summarize(items, q=5)

In [5]:
df = all_sales()
df

,item,sale_amount,sale_date,sale_id,store,store_address,store_city,store_state,store_zipcode,item_brand,item_name,item_price,item_upc12,item_upc14
0,1,13.0,"Tue, 01 Jan 2013 00:00:00 GMT",1,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
1,1,11.0,"Wed, 02 Jan 2013 00:00:00 GMT",2,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
2,1,14.0,"Thu, 03 Jan 2013 00:00:00 GMT",3,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
3,1,13.0,"Fri, 04 Jan 2013 00:00:00 GMT",4,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
4,1,10.0,"Sat, 05 Jan 2013 00:00:00 GMT",5,1,12125 Alamo Ranch Pkwy,San Antonio,TX,78253,Riceland,Riceland American Jazmine Rice,0.84,35200264013,35200264013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
912995,50,63.0,"Wed, 27 Dec 2017 00:00:00 GMT",912996,10,8503 NW Military Hwy,San Antonio,TX,78231,Choice,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221
912996,50,59.0,"Thu, 28 Dec 2017 00:00:00 GMT",912997,10,8503 NW Military Hwy,San Antonio,TX,78231,Choice,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221
912997,50,74.0,"Fri, 29 Dec 2017 00:00:00 GMT",912998,10,8503 NW Military Hwy,San Antonio,TX,78231,Choice,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221
912998,50,62.0,"Sat, 30 Dec 2017 00:00:00 GMT",912999,10,8503 NW Military Hwy,San Antonio,TX,78231,Choice,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221
912999,50,82.0,"Sun, 31 Dec 2017 00:00:00 GMT",913000,10,8503 NW Military Hwy,San Antonio,TX,78231,Choice,Choice Organic Teas Black Tea Classic Black - ...,5.20,47445919221,47445919221

In [8]:
summarize(df)

    DataFrame .head():
    -----------------
|    |   item |   sale_amount | sale_date                     |   sale_id |   store | store_address          | store_city   | store_state   |   store_zipcode | item_brand   | item_name                      |   item_price |   item_upc12 |   item_upc14 |
|---:|-------:|--------------:|:------------------------------|----------:|--------:|:-----------------------|:-------------|:--------------|----------------:|:-------------|:-------------------------------|-------------:|-------------:|-------------:|
|  0 |      1 |            13 | Tue, 01 Jan 2013 00:00:00 GMT |         1 |       1 | 12125 Alamo Ranch Pkwy | San Antonio  | TX            |           78253 | Riceland     | Riceland American Jazmine Rice |         0.84 |  35200264013 |  35200264013 |
|  1 |      1 |            11 | Wed, 02 Jan 2013 00:00:00 GMT |         2 |       1 | 12125 Alamo Ranch Pkwy | San Antonio  | TX            |           78253 | Riceland     | Riceland American Jazmine Rice |         0.84 |  35200264013 |  35200264013 |
|  2 |      1 |            14 | Thu, 03 Jan 2013 00:00:00 GMT |         3 |       1 | 12125 Alamo Ranch Pkwy | San Antonio  | TX            |           78253 | Riceland     | Riceland American Jazmine Rice |         0.84 |  35200264013 |  35200264013 |
|  3 |      1 |            13 | Fri, 04 Jan 2013 00:00:00 GMT |         4 |       1 | 12125 Alamo Ranch Pkwy | San Antonio  | TX            |           78253 | Riceland     | Riceland American Jazmine Rice |         0.84 |  35200264013 |  35200264013 |
|  4 |      1 |            10 | Sat, 05 Jan 2013 00:00:00 GMT |         5 |       1 | 12125 Alamo Ranch Pkwy | San Antonio  | TX            |           78253 | Riceland     | Riceland American Jazmine Rice |         0.84 |  35200264013 |  35200264013 |

    DataFrame .info():
    -----------------

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 913000 entries, 0 to 912999
Data columns (total 14 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   item           913000 non-null  int64
 1   sale_amount    913000 non-null  float64
 2   sale_date      913000 non-null  object
 3   sale_id        913000 non-null  int64
 4   store          913000 non-null  int64
 5   store_address  913000 non-null  object
 6   store_city     913000 non-null  object
 7   store_state    913000 non-null  object
 8   store_zipcode  913000 non-null  object
 9   item_brand     913000 non-null  object
 10  item_name      913000 non-null  object
 11  item_price     913000 non-null  float64
 12  item_upc12     913000 non-null  object
 13  item_upc14     913000 non-null  object
dtypes: float64(2), int64(3), object(9)
memory usage: 97.5+ MB
None
Number of Columns with nulls: 0

    DataFrame .describe():
    -----------------
|             |   count |        mean |          std |   min |       25% |        50% |       75% |       max |
|:------------|--------:|------------:|-------------:|------:|----------:|-----------:|----------:|----------:|
| item        |  913000 |     25.5    |     14.4309  |   1   |     13    |     25.5   |     38    |     50    |
| sale_amount |  913000 |     52.2503 |     28.8011  |   0   |     30    |     47     |     70    |    231    |
| sale_id     |  913000 | 456500      | 263561       |   1   | 228251    | 456500     | 684750    | 913000    |
| store       |  913000 |      5.5    |      2.87228 |   1   |      3    |      5.5   |      8    |     10    |
| item_price  |  913000 |      5.1604 |      2.73776 |   0.6 |      2.97 |      5.195 |      7.52 |      9.64 |

    Null Value Assessments:
    -----------------

        Nulls By Column:
| num_rows_missing   | percent_missing   |
|--------------------|-------------------|
    -----------------

        Nulls By Row:
|    |   num_cols_missing |   percent_missing |   count |
|---:|-------------------:|------------------:|--------:|
|  0 |                  0 |                 0 |  913000 |

    DataFrame .value_counts():
    -----------------

Column Name:  item
--------------
Numerical: Divided by Quartile
 -  10 bins

|              |   item |
|:-------------|-------:|
| (0.95, 5.9]  |  91300 |
| (5.9, 10.8]  |  91300 |
| (10.8, 15.7] |  91300 |
| (15.7, 20.6] |  91300 |
| (20.6, 25.5] |  91300 |
| (25.5, 30.4] |  91300 |
| (30.4, 35.3] |  91300 |
| (35.3, 40.2] |  91300 |
| (40.2, 45.1] |  91300 |
| (45.1, 50.0] |  91300 |

-------------
Column Name:  sale_amount
--------------
Numerical: Divided by Quartile
 -  10 bins

|                |   sale_amount |
|:---------------|--------------:|
| (-0.232, 23.1] |        141304 |
| (23.1, 46.2]   |        309995 |
| (46.2, 69.3]   |        232808 |
| (69.3, 92.4]   |        136482 |
| (92.4, 115.5]  |         62877 |
| (115.5, 138.6] |         22559 |
| (138.6, 161.7] |          5865 |
| (161.7, 184.8] |          1009 |
| (184.8, 207.9] |            96 |
| (207.9, 231.0] |             5 |

-------------
Column Name:  sale_date
--------------
Categorical:
 -  1826 Categories

 Tue, 01 Jan 2013 00:00:00 GMT    500
Wed, 11 May 2016 00:00:00 GMT    500
Mon, 09 May 2016 00:00:00 GMT    500
Sun, 08 May 2016 00:00:00 GMT    500
Sat, 07 May 2016 00:00:00 GMT    500
                                ...
Fri, 29 Aug 2014 00:00:00 GMT    500
Thu, 28 Aug 2014 00:00:00 GMT    500
Wed, 27 Aug 2014 00:00:00 GMT    500
Tue, 26 Aug 2014 00:00:00 GMT    500
Sun, 31 Dec 2017 00:00:00 GMT    500
Name: sale_date, Length: 1826, dtype: int64


-------------
Column Name:  sale_id
--------------
Numerical: Divided by Quartile
 -  10 bins

|                      |   sale_id |
|:---------------------|----------:|
| (-912.0, 91300.9]    |     91300 |
| (91300.9, 182600.8]  |     91300 |
| (182600.8, 273900.7] |     91300 |
| (273900.7, 365200.6] |     91300 |
| (365200.6, 456500.5] |     91300 |
| (456500.5, 547800.4] |     91300 |
| (547800.4, 639100.3] |     91300 |
| (639100.3, 730400.2] |     91300 |
| (730400.2, 821700.1] |     91300 |
| (821700.1, 913000.0] |     91300 |

-------------
Column Name:  store
--------------
Numerical: Divided by Quartile
 -  10 bins

|             |   store |
|:------------|--------:|
| (0.99, 1.9] |   91300 |
| (1.9, 2.8]  |   91300 |
| (2.8, 3.7]  |   91300 |
| (3.7, 4.6]  |   91300 |
| (4.6, 5.5]  |   91300 |
| (5.5, 6.4]  |   91300 |
| (6.4, 7.3]  |   91300 |
| (7.3, 8.2]  |   91300 |
| (8.2, 9.1]  |   91300 |
| (9.1, 10.0] |   91300 |

-------------
Column Name:  store_address
--------------
Categorical:
 -  10 Categories

|                         |   store_address |
|:------------------------|----------------:|
| 12125 Alamo Ranch Pkwy  |           91300 |
| 9255 FM 471 West        |           91300 |
| 2118 Fredericksburg Rdj |           91300 |
| 516 S Flores St         |           91300 |
| 1520 Austin Hwy         |           91300 |
| 1015 S WW White Rd      |           91300 |
| 12018 Perrin Beitel Rd  |           91300 |
| 15000 San Pedro Ave     |           91300 |
| 735 SW Military Dr      |           91300 |
| 8503 NW Military Hwy    |           91300 |

-------------
Column Name:  store_city
--------------
Categorical:
 -  1 Categories

|             |   store_city |
|:------------|-------------:|
| San Antonio |       913000 |

-------------
Column Name:  store_state
--------------
Categorical:
 -  1 Categories

|    |   store_state |
|:---|--------------:|
| TX |        913000 |

-------------
Column Name:  store_zipcode
--------------
Categorical:
 -  10 Categories

|       |   store_zipcode |
|------:|----------------:|
| 78253 |           91300 |
| 78251 |           91300 |
| 78201 |           91300 |
| 78204 |           91300 |
| 78218 |           91300 |
| 78220 |           91300 |
| 78217 |           91300 |
| 78232 |           91300 |
| 78221 |           91300 |
| 78231 |           91300 |

-------------
Column Name:  item_brand
--------------
Categorical:
 -  49 Categories

|                        |   item_brand |
|:-----------------------|-------------:|
| Usda Produce           |        36520 |
| Riceland               |        18260 |
| Sundown Naturals       |        18260 |
| Heinz                  |        18260 |
| Petmate                |        18260 |
| Zhenas Gypsy Tea       |        18260 |
| Barefoot               |        18260 |
| The First Years        |        18260 |
| Halls                  |        18260 |
| Natures Way            |        18260 |
| Deerfields Gluten Free |        18260 |
| Nakano                 |        18260 |
| Munchies               |        18260 |
| Triaminic              |        18260 |
| Amys                   |        18260 |
| P.f. Changs            |        18260 |
| Moms Best Naturals     |        18260 |
| Ferrara                |        18260 |
| Elmers                 |        18260 |
| Kelloggs               |        18260 |
| Mama Marys             |        18260 |
| Bear Naked             |        18260 |
| Dove                   |        18260 |
| Easy-off               |        18260 |
| Morton                 |        18260 |
| Hood                   |        18260 |
| Caress                 |        18260 |
| Mueller                |        18260 |
| Earths Best            |        18260 |
| Boars Head             |        18260 |
| Back To Nature         |        18260 |
| Sally Hansen           |        18260 |
| Twinings Of London     |        18260 |
| Lea & Perrins          |        18260 |
| Van De Kamps           |        18260 |
| Ahold                  |        18260 |
| Honest Tea             |        18260 |
| Garnier Nutritioniste  |        18260 |
| Smart Living           |        18260 |
| Pamprin                |        18260 |
| Suave                  |        18260 |
| Burts Bees             |        18260 |
| Ducal                  |        18260 |
| Scotch                 |        18260 |
| Careone                |        18260 |
| Doctors Best           |        18260 |
| Betty Crocker          |        18260 |
| Reese                  |        18260 |
| Choice                 |        18260 |

-------------
Column Name:  item_name
--------------
Categorical:
 -  50 Categories

 Riceland American Jazmine Rice                                                                       18260
Sundown Naturals Essential Electrolytes Tropical Punch Watermelon And Fruit Punch Gummies - 60 Ct    18260
Guava                                                                                                18260
Heinz Tomato Ketchup - 2 Ct                                                                          18260
Petmate Booda Bones Steak Bacon & Chicken Flavors - 9 Ct                                             18260
Zhenas Gypsy Tea Herbal Red Tea Sachets Fire Light Chai - 22 Ct                                      18260
Barefoot Pinot Grigio  187                                                                           18260
Tomy The First Years Gumdrop Orthodontic Pacifiers 6m+ - 2ct                                         18260
Halls Menthol Cough Suppresant/oral Anesthetic Drops Honey-lemon - 30 Ct                             18260
Natures Way Forskohlii - 60 Ct                                                                       18260
Rice Bran Gluten Free Dinner Rolls Plain                                                             18260
Nakano Seasoned Rice Vinegar Original                                                                18260
Munchies Sandwich Crackers Cheddar Cheese On Golden Toast Crackers - 8 Pk                            18260
Caress Velvet Bliss Ultra Silkening Beauty Bar - 6 Ct                                                18260
Amys Light & Lean Spaghetti Italiano                                                                 18260
P.f. Changs Home Menu Meal For Two Beef With Broccoli                                                18260
Moms Best Naturals Cereal Toasted Cinnamon Squares                                                   18260
Ferrara Vanilla Syrup                                                                                18260
Elmers Board Mate Dual Tip Glue Pen                                                                  18260
Kelloggs Disney Pixar Cars 2 Cereal                                                                  18260
Pizza Sauce                                                                                          18260
Bear Naked Fit Almond Crisp 100 Percent Natural Energy Cereal                                        18260
Dove Men + Care Antiperspirant Deodorant Cool Silver                                                 18260
Easy-off Oven Cleaner Lemon Scent                                                                    18260
Morton Kosher Salt Coarse                                                                            18260
Triaminic Syrup Night Time Cold & Cough Grape 4oz                                                    18260
Hood Latte Iced Coffee Drink Vanilla Latte                                                           18260
Smart Living Charcoal Lighter Fluid                                                                  18260
Earths Best Organic Fruit Yogurt Smoothie Mixed Berry                                                18260
Boars Head Sliced White American Cheese - 120 Ct                                                     18260
Back To Nature Gluten Free White Cheddar Rice Thin Crackers                                          18260
Sally Hansen Nail Color Magnetic 903 Silver Elements                                                 18260
Twinings Of London Classics Lady Grey Tea - 20 Ct                                                    18260
Lea & Perrins Marinade In-a-bag Cracked Peppercorn                                                   18260
Van De Kamps Fillets Beer Battered - 10 Ct                                                           18260
Ahold Cocoa Almonds                                                                                  18260
Honest Tea Peach White Tea                                                                           18260
Mueller Sport Care Basic Support Level Medium Elastic Knee Support                                   18260
Garnier Nutritioniste Moisture Rescue Fresh Cleansing Foam                                           18260
Pamprin Maximum Strength Multi-symptom Menstrual Pain Relief                                         18260
Suave Naturals Moisturizing Body Wash Creamy Tropical Coconut                                        18260
Burts Bees Daily Moisturizing Cream Sensitive                                                        18260
Ducal Refried Red Beans                                                                              18260
Scotch Removable Clear Mounting Squares - 35 Ct                                                      18260
Careone Family Comb Set - 8 Ct                                                                       18260
Plums Black                                                                                          18260
Doctors Best Best Curcumin C3 Complex 1000mg Tablets - 120 Ct                                        18260
Betty Crocker Twin Pack Real Potatoes Scalloped 2 Pouches For 2 Meals - 2 Pk                         18260
Reese Mandarin Oranges Segments In Light Syrup                                                       18260
Choice Organic Teas Black Tea Classic Black - 16 Ct                                                  18260
Name: item_name, dtype: int64


-------------
Column Name:  item_price
--------------
Numerical: Divided by Quartile
 -  10 bins

|                |   item_price |
|:---------------|-------------:|
| (0.59, 1.504]  |       109560 |
| (1.504, 2.408] |        54780 |
| (2.408, 3.312] |       109560 |
| (3.312, 4.216] |        91300 |
| (4.216, 5.12]  |        54780 |
| (5.12, 6.024]  |       127820 |
| (6.024, 6.928] |        54780 |
| (6.928, 7.832] |       109560 |
| (7.832, 8.736] |       109560 |
| (8.736, 9.64]  |        91300 |

-------------
Column Name:  item_upc12
--------------
Categorical:
 -  50 Categories

 35200264013     18260
30768540548     18260
719175900007    18260
13000001038     18260
723503568678    18260
652790100226    18260
8500004528      18260
71463060078     18260
312546628694    18260
33674100066     18260
610358991525    18260
73575295003     18260
28400029254     18260
11111065925     18260
42272008063     18260
31000670016     18260
883978129115    18260
71403000379     18260
26000001403     18260
38000542237     18260
35457770664     18260
884623708976    18260
79400271631     18260
62338879772     18260
24600017008     18260
300436344045    18260
44100117428     18260
688267084225    18260
23923330139     18260
208528800007    18260
759283100036    18260
74170388732     18260
70177154004     18260
51600080015     18260
19600923015     18260
688267141676    18260
657622604842    18260
74676640211     18260
603084234561    18260
41167300121     18260
79400847201     18260
792850014008    18260
88313590791     18260
21200725340     18260
41520035646     18260
204040000000    18260
753950001954    18260
16000288829     18260
70670009658     18260
47445919221     18260
Name: item_upc12, dtype: int64


-------------
Column Name:  item_upc14
--------------
Categorical:
 -  50 Categories

 35200264013     18260
30768540548     18260
719175900007    18260
13000001038     18260
723503568678    18260
652790100226    18260
8500004528      18260
71463060078     18260
312546628694    18260
33674100066     18260
610358991525    18260
73575295003     18260
28400029254     18260
11111065925     18260
42272008063     18260
31000670016     18260
883978129115    18260
71403000379     18260
26000001403     18260
38000542237     18260
35457770664     18260
884623708976    18260
79400271631     18260
62338879772     18260
24600017008     18260
300436344045    18260
44100117428     18260
688267084225    18260
23923330139     18260
208528800007    18260
759283100036    18260
74170388732     18260
70177154004     18260
51600080015     18260
19600923015     18260
688267141676    18260
657622604842    18260
74676640211     18260
603084234561    18260
41167300121     18260
79400847201     18260
792850014008    18260
88313590791     18260
21200725340     18260
41520035646     18260
204040000000    18260
753950001954    18260
16000288829     18260
70670009658     18260
47445919221     18260
Name: item_upc14, dtype: int64


-------------
-----------------
---End of Line---

<a id="6"> </a>
<div class= "alert alert-box alert-info">
</div>

***
## 6. Acquire the Open Power Systems Data for Germany, which has been rapidly expanding its renewable energy production in recent years. The data set includes country-wide totals of electricity consumption, wind power production, and solar power production for 2006-2017. You can get the data [here:](https://raw.githubusercontent.com/jenfly/opsd/master/opsd_germany_daily.csv)

[__<u>TOP</u>__](#TOP)

In [6]:
opsd_df = open_power_systems_data()

opsd_df

            Date  Consumption     Wind   Solar  Wind+Solar
0     2006-01-01   1069.18400      NaN     NaN         NaN
1     2006-01-02   1380.52100      NaN     NaN         NaN
2     2006-01-03   1442.53300      NaN     NaN         NaN
3     2006-01-04   1457.21700      NaN     NaN         NaN
4     2006-01-05   1477.13100      NaN     NaN         NaN
...          ...          ...      ...     ...         ...
4378  2017-12-27   1263.94091  394.507  16.530     411.037
4379  2017-12-28   1299.86398  506.424  14.162     520.586
4380  2017-12-29   1295.08753  584.277  29.854     614.131
4381  2017-12-30   1215.44897  721.247   7.467     728.714
4382  2017-12-31   1107.11488  721.176  19.980     741.156

[4383 rows x 5 columns]

<a id="7"> </a>
<div class= "alert alert-box alert-info">
</div>

***
## 7. Make sure all the work that you have done above is reproducible. That is, you should put the code above into separate functions in the acquire.py file and be able to re-run the functions and get the same data.

[__<u>TOP</u>__](#TOP)

In [ ]:
# Check 